Remove error word from info logs *40140
Vivino/gorm pull request #9
Opened 2020-10-13 09:19 UTC by tolya95x106

Story reference: https://tickets.vivino.com/issues/40140

## How did you implement this?

Changed mysql errors to be logged without error word in info logs

2020-10-14 09:10 UTC, eikmadsen requested changes

2020-10-14 09:10 UTC, eikmadsen commented on logger.go
> +			var message interface{}
The entire gorm package is database agnostic (until now) ... 
I suggest you revert your changes here, and instead override the LogFormatter in cfgrevel package.

2020-10-15 13:00 UTC, eikmadsen requested changes
No need to delete all the existing code. Just override it in cfgrevel as you are doing now ;-)

2020-12-14 15:18 UTC, eikmadsen requested changes
Why is this in the GORM fork ? It could a function in go-tools or go-common instead.  
They LogFormatter var is exported so you can override it locally where you need it

2020-12-14 17:06 UTC, tolya95x106 commented
This is refactoring and no new functionality.

2020-12-14 23:02 UTC, eikmadsen commented
I see, difficult to tell from the changes without doing a very thorough review. 
Could we skip the refactor ? If you are setting the LogFormatter, then all we get from these changes are potential merge conflicts when upgrading gorm.

2020-12-15 10:16 UTC, closed without merging